server:
  port: 9088
  servlet:
    contextPath: /vma
    
logging:
  level:
    root: INFO
  pattern:
    console: "${spring.application.name} > %-5p : %40.40c{1}[%20.20M:%4L] - %m%n"

org:
  hibernate:
    sql: true
    
spring:
  application:
    name: vma
  jackson:
    dateFormat: yyyy-MM-dd'T'HH:mm:ssZ
    timeZone: America/Bogota
  batch:
    jdbc:
      initializeSchema: never
  cache:
    type: none
  output:
    ansi:
      enabled: DETECT
  jpa:
    hibernate:
     ddl-auto: update
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

myapp:
  datasource:
    remote-secret-ops: http://10.10.3.115:3000
    token: 0311874a-a7c1-4d74-b144-2f597f823359
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #app-front-url: https://appsdev.sunass.gob.pe/vma/#
  dias-expiracion: 7
  
  alfresco:
    remote-secret-ops: http://10.10.3.115:3000
    token: 0311874a-a7c1-4d74-b144-2f597f823359
    #url: https://alfrescodev.sunass.gob.pe/
    #user: uvma
    #password: =okKmqV*7637
    #carpeta: VMA
    #spaceStore: 68b878c9-0106-415f-b4e0-3be12bcb2ad8

cors:
  urls: http://localhost:4501,http://10.10.3.184
        
security:
  jwt:
    expiration-minutes: 60

ldap:
  cn: OU=Usuarios,DC=sunass,DC=gob,DC=pe
  cnSearch: DC=sunass,DC=gob,DC=pe
  group: GS_GSF
  user: userval
  password: Validador2000
  prefix: '@sunass.gob.pe'
  timeout: 3000
  url: ldap://10.10.3.9:389

alfresco:
  url: 
  user: uvma
  password: 
  carpeta: VMA
  spaceStore: 
  