server:
  port: 8085
  servlet:
    contextPath: /vma
  

logging:
  level:
    root: INFO
  pattern:
    console: "${spring.application.name} > %-5p : %40.40c{1}[%20.20M:%4L] - %m%n"

org:
  hibernate:
    sql: true
    
spring:
  application:
    name: vma
  jackson:
    dateFormat: yyyy-MM-dd'T'HH:mm:ssZ
    timeZone: America/Bogota
  batch:
    jdbc:
      initializeSchema: never
  cache:
    type: none
  output:
    ansi:
      enabled: DETECT
      
  jpa:
    hibernate:
     ddl-auto: update
     
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
     
  mail:  #para localhost
    host: smtp.gmail.com
    port: 587
    username: apiconnectibm1@gmail.com
    password: cgat smzw bpuo oopa
    properties:
      mail:
        smtp:
         auth: true
         starttls:
            enable: true
            
myapp:
  datasource:
    url: jdbc:postgresql://localhost:5432/vma
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
  app-front-url: http://localhost:4200/#
  dias-expiracion: 2

cors:
  urls: 
        
security:
  jwt:
    expiration-minutes: 60
    secret-key: RDN2M2wwcDNyIDNuIFN1TjRTUyBWNE0wNTY3IDEyMzQ1Njc4OSBBQkNhYmM=

ldap:
  cn: OU=Usuarios,DC=sunass,DC=gob,DC=pe
  cnSearch: DC=sunass,DC=gob,DC=pe
  group: GS_GSF
  password: Validador2000
  prefix: '@sunass.gob.pe'
  timeout: 3000
  url: ldap://10.10.3.9:389
  user: userval
  

